name: cphmm  # Name of the environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - ipykernel
  - pyarrow # For accessing compressed SNV catalogues
  - pandas
  - biopython
